### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by bjones1** [hlamer/enki#277]
Running with current head. I'll take a look at the test_markdown failure -- any ideas on the others?

```
======================================================================
ERROR: test_4 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 76, in test_4
    with open(fullPath) as file_:
IOError: [Errno 2] No such file or directory: 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\
dir1/dir2/thefile.txt'

======================================================================
FAIL: test_markdown (test_plugins.test_preview.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_preview.py", lin
e 167, in test_markdown
    self._doBasicTest('md')
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_preview.py", lin
e 100, in _doBasicTest
    self._assertHtmlReady(lambda: self.createFile('.'.join([name, extension]),
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_preview.py", lin
e 92, in _assertHtmlReady
    self.assertEmits(start, self._widget().webView.page().mainFrame().loadFinished, timeout)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 394, in assertEmits
    timeoutMs, expectedSignalParams))
AssertionError: False is not true

======================================================================
FAIL: test_2 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 50, in test_2
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhefile.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\thefile.txt'

======================================================================
FAIL: test_3 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 64, in test_3
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhefile.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\thefile.txt'

======================================================================
FAIL: test_6 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 108, in test_6
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhe file.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\the file.txt'

======================================================================
FAIL: test_7 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 318, in <lambda>
    QTimer.singleShot(20, lambda: timerCallback(1))
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 311, in timerCallback
    runInDialogFunc(dialog)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 124, in inDialogFunc
    'f ' + fullPath.replace(' ', '\\ '))
AssertionError: u'f c:\\users\\bjones\\appdata\\local\\temp\\enki-tests/the' != 'f c:\\users\\bjones
\\appdata\\local\\temp\\enki-tests\\the\\ file.txt'

----------------------------------------------------------------------
Ran 281 tests in 98.363s

FAILED (failures=5, errors=1, skipped=24, expected failures=3)
```

**Comment by hlamer** [comment]
Workspace tests should pass on Windows now.

I'm surprised why markdown test failed. Could you run it once more to check if it is a timing problem?

**Comment by bjones1** [comment]
I re-ran the tests and see that the Markdown failure was just a timing problem; it disappears on a second run. The other failures still remain (using head of 7c18e1caf5b0d8e10d9e9a1dbcd24366588cb668).

```
======================================================================
ERROR: test_4 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 76, in test_4
    with open(fullPath) as file_:
IOError: [Errno 2] No such file or directory: 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\
dir1/dir2/thefile.txt'

======================================================================
FAIL: test_2 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 50, in test_2
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhefile.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\thefile.txt'

======================================================================
FAIL: test_3 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 64, in test_3
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhefile.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\thefile.txt'

======================================================================
FAIL: test_6 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 97, in execWithArgs
    func(*args)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 108, in test_6
    self.assertEqual(core.workspace().currentDocument().filePath(), fullPath)
AssertionError: u'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\c:usersbjonesappdatalocaltemp
enki-teststhe file.txt' != 'c:\\users\\bjones\\appdata\\local\\temp\\enki-tests\\the file.txt'

======================================================================
FAIL: test_7 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 318, in <lambda>
    QTimer.singleShot(20, lambda: timerCallback(1))
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 311, in timerCallback
    runInDialogFunc(dialog)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 124, in inDialogFunc
    'f ' + fullPath.replace(' ', '\\ '))
AssertionError: u'f c:\\users\\bjones\\appdata\\local\\temp\\enki-tests/the' != 'f c:\\users\\bjones
\\appdata\\local\\temp\\enki-tests\\the\\ file.txt'

----------------------------------------------------------------------
```

**Comment by bjones1** [comment]
Oops. Ignore the above. Retesting on 7c18e1caf5b0d8e10d9e9a1dbcd24366588cb668 shows only one failure:

```
======================================================================
FAIL: test_7 (test_plugins.test_workspace_commands.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 318, in <lambda>
    QTimer.singleShot(20, lambda: timerCallback(1))
  File "C:\Users\bjones\Documents\enki_all\enki\tests\base.py", line 311, in timerCallback
    runInDialogFunc(dialog)
  File "C:\Users\bjones\Documents\enki_all\enki\tests\test_lib\..\test_plugins\test_workspace_comman
ds.py", line 124, in inDialogFunc
    'f ' + fullPath.replace('\\', '\\\\').replace(' ', '\\ '))
AssertionError: u'f c:\\users\\bjones\\appdata\\local\\temp\\enki-tests/the' != 'f c:\\\\users\\\\bj
ones\\\\appdata\\\\local\\\\temp\\\\enki-tests\\\\the\\ file.txt'

----------------------------------------------------------------------
```
