### ISSUE TITLE
Crash if closed when loading

### ISSUE THREAD

**Issue by hlamer** [hlamer/enki#296]
By @vi

```
QThread: Destroyed while thread is still running
QThread: Destroyed while thread is still running
CRITICAL:root:Traceback (most recent call last):
  File "/mnt/src/git/enki/bin/../enki/plugins/fuzzyopen/fuzzyopen.py", line 77, in run
    self.itemsReady.emit(results)
RuntimeError: wrapped C/C++ object of type ScannerThread has been deleted
CRITICAL:root:Traceback (most recent call last):
  File "/mnt/src/git/enki/bin/../enki/plugins/fuzzyopen/fuzzyopen.py", line 77, in run
    self.itemsReady.emit(results)
RuntimeError: wrapped C/C++ object of type ScannerThread has been deleted
```

**Comment by hlamer** [comment]
Fixed
