### ISSUE TITLE
Support line numbers

### ISSUE THREAD

**Issue by hlamer** [hlamer/enki#300]
I typed LME in FuzzyLocator, it showed the correct file. I continued: LME 23 meaning "Open 23'th line of this file". The file disappeared. I pressed Enter:

```
Traceback (most recent call last):
  File "/mnt/src/git/enki/bin/../enki/plugins/fuzzyopen/fuzzyopen.py", line 180, in _onEnter
    path = self._model.path(index)
  File "/mnt/src/git/enki/bin/../enki/plugins/fuzzyopen/fuzzyopen.py", line 125, in path
    return self._items[index.row()][0]
IndexError: list index out of range
```

By @vi

**Comment by hlamer** [comment]
Done
